[package]
name = "keyper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.8.8"
serde = { version = "1.0.195", features = ["derive"] }
log = "0.4.20"
simple_logger = "4.3.3"
